services:
  redis-stream:
    image: redis:latest
    container_name: redis-stream
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  redis-user:
    image: redis:latest
    container_name: redis-user
    ports:
      - "6380:6380"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_user:/data

  postgres-user:
    image: postgres:latest
    container_name: postgres-db1
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data1:/var/lib/postgresql/data

  postgres-notification:
    image: postgres:latest
    container_name: postgres-db2
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: notification
    ports:
      - "5433:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data

  postgres-salary:
    image: postgres:latest
    container_name: postgres-db3
    environment:
      POSTGRES_USER: user3
      POSTGRES_PASSWORD: password3
      POSTGRES_DB: salary
    ports:
      - "5434:5432"
    volumes:
      - postgres_data3:/var/lib/postgresql/data

volumes:
  redis_data:
  redis_user:
  postgres_data1:
  postgres_data2:
  postgres_data3:
