version: '3.8'

services:
#  auth:
#    build:
#      context: ./auth
#    image: litpon92/auth-salaryc:latest
#    ports:
#      - "8084:8084"
#    networks:
#      - shared_network
#
#  user:
#    build:
#      context: ./user
#    image: litpon92/user-salaryc:latest
#    ports:
#      - "8082:8082"
#    networks:
#      - shared_network

#  salary:
#    build:
#      context: ./salary
#    image: litpon92/salary-salaryc:latest
#
#  gateway:
#    build:
#      context: ./gateway
#    image: litpon92/gateway-salaryc:latest
#    ports:
#      - "8080:8080"
#    deploy:
#      replicas: 1
#      resources:
#        limits:
#          memory: 512M
#      restart_policy:
#        condition: on-failure
#    networks:
#      - shared_network
#
#  notification:
#    build:
#      context: ./notification
#    image: litpon92/gateway-notification:latest

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure


  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1G
      restart_policy:
        condition: on-failure


  redis-user:
    image: redis:latest
    container_name: redis-user
    ports:
      - "6380:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_user:/data

  postgres-user:
    image: postgres:latest
    container_name: postgres-db1
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data1:/var/lib/postgresql/data

  postgres-notification:
    image: postgres:latest
    container_name: postgres-db2
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: notification
    ports:
      - "5433:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data


  postgres-salary:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    environment:
      POSTGRES_USER: user3
      POSTGRES_PASSWORD: password3
      POSTGRES_DB: salary
    ports:
      - "5434:5432"
    volumes:
      - postgres_data3:/var/lib/postgresql/data


volumes:
  redis_data:
  redis_user:
  postgres_data1:
  postgres_data2:
  postgres_data3:

