spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-svc:8080  # 마이크로서비스의 주소
          predicates:
            - Path=/api/auth/**

#        - id: user-service
#          uri: http://user-svc:8080  # 다른 마이크로서비스의 주소
#          predicates:
#            - Path=/api/users/**
management:
  endpoints:
    web:
      exposure:
        include: "*"